from __future__ import print_function
import keras
from keras.datasets import cifar10
from keras_preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.advanced_activations import LeakyReLU, PReLU
import matplotlib.pyplot as plt
import os

batch_size = 8
num_classes = 10
epochs = 100
data_augmentation = False
num_predictions = 20
save_dir = os.path.join(os.getcwd(), 'saved_models')
model_name = 'keras_cifar10_trained_model.h5'
resize_shape = (32, 32, 3)

# The data, split between train and test sets:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# Convert class vectors to binary class matrices.
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

#setup model
#cifar_model = M.msdnet(3, (2, 8), 10, use_dropout=True, dropout=0.25) #3, (2,2), nClasses
rms_model = Sequential()
rms_model.add(Conv2D(32, kernel_size=(3, 3), strides=(1, 1), activation='linear', padding='same', input_shape=resize_shape))
rms_model.add(LeakyReLU(alpha=0.01))
rms_model.add(MaxPooling2D((2, 2), padding='same'))
# rms_model.add(Dropout(0.7))
rms_model.add(Conv2D(64, (3, 3), activation='linear', padding='same'))
rms_model.add(LeakyReLU(alpha=0.01))
rms_model.add(MaxPooling2D(pool_size=(2, 2), padding='same'))
# rms_model.add(Dropout(0.6))
rms_model.add(Conv2D(128, (3, 3), activation='linear', padding='same'))
rms_model.add(LeakyReLU(alpha=0.01))
rms_model.add(MaxPooling2D(pool_size=(2, 2), padding='same'))
# rms_model.add(Dropout(0.6))
rms_model.add(Flatten())
rms_model.add(Dense(4096, activation='linear')) #tanh
rms_model.add(LeakyReLU(alpha=0.01))
# rms_model.add(Dropout(0.9))
rms_model.add(Dense(2048, activation='linear')) #sigmoid
rms_model.add(LeakyReLU(alpha=0.01))
# rms_model.add(Dropout(0.7))
rms_model.add(Dense(1024, activation='linear')) #sigmoid
rms_model.add(LeakyReLU(alpha=0.01))
# rms_model.add(Dropout(0.6))
rms_model.add(Dense(num_classes, activation='softmax'))

print("Final layers added")

#keras.losses.categorical_crossentropy
rms_model.compile(loss='categorical_crossentropy', optimizer=keras.optimizers.Adam(clipnorm=1., clipvalue=0.5), metrics=['accuracy'])

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

hist = 0

if not data_augmentation:
    print('Not using data augmentation.')
    hist = rms_model.fit(x_train, y_train,
              batch_size=batch_size,
              epochs=epochs,
              validation_data=(x_test, y_test),
              shuffle=True)
else:
    print('Using real-time data augmentation.')
    # This will do preprocessing and realtime data augmentation:
    datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        zca_epsilon=1e-06,  # epsilon for ZCA whitening
        rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
        # randomly shift images horizontally (fraction of total width)
        width_shift_range=0.1,
        # randomly shift images vertically (fraction of total height)
        height_shift_range=0.1,
        shear_range=0.,  # set range for random shear
        zoom_range=0.,  # set range for random zoom
        channel_shift_range=0.,  # set range for random channel shifts
        # set mode for filling points outside the input boundaries
        fill_mode='nearest',
        cval=0.,  # value used for fill_mode = "constant"
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False,  # randomly flip images
        # set rescaling factor (applied before any other transformation)
        rescale=None,
        # set function that will be applied on each input
        preprocessing_function=None,
        # image data format, either "channels_first" or "channels_last"
        data_format='channels_last',
        # fraction of images reserved for validation (strictly between 0 and 1)
        validation_split=0.0)

    # Compute quantities required for feature-wise normalization
    # (std, mean, and principal components if ZCA whitening is applied).
    datagen.fit(x_train)

    # Fit the model on the batches generated by datagen.flow().
    rms_model.fit_generator(datagen.flow(x_train, y_train,
                                     batch_size=batch_size),
                        epochs=epochs,
                        validation_data=(x_test, y_test),
                        workers=4)

# Save model and weights
if not os.path.isdir(save_dir):
    os.makedirs(save_dir)
model_path = os.path.join(save_dir, model_name)
rms_model.save(model_path)
print('Saved trained model at %s ' % model_path)

accuracy = hist.history['acc']
val_accuracy = hist.history['val_acc']
loss = hist.history['loss']
val_loss = hist.history['val_loss']
epochs = range(len(accuracy))
plt.plot(epochs, accuracy, 'bo', label='Training accuracy')
plt.plot(epochs, val_accuracy, 'b', label='Validation accuracy')
plt.title('Training and validation accuracy')
plt.legend()
plt.figure()
plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()
plt.show()

# Score trained model.
scores = rms_model.evaluate(x_test, y_test, verbose=1)
print('Test loss:', scores[0])
print('Test accuracy:', scores[1])
